In [134]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()

In [135]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [136]:
digits.data.shape

(1797, 64)

In [141]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data, digits.target, test_size=0.2)

In [142]:
lr = LogisticRegression(max_iter=200)
lr.fit(x_train,y_train)
lr.score(x_train,y_train)

1.0

In [143]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_train,y_train)

0.9958246346555324

In [144]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_train,y_train)

1.0

In [171]:
def performance(model,x_train,x_test,y_train,y_test):
    score = model.score(x_test,y_test)
    return score

In [176]:
print('Logistic Regression:',performance(lr,x_train,x_test,y_train,y_test))
print('SVM:',performance(svm,x_train,x_test,y_train,y_test))
print('Random Forest:',performance(rf,x_train,x_test,y_train,y_test))


Logistic Regression: 0.9966666666666667
SVM: 1.0
Random Forest: 0.9966666666666667


In [177]:
for a in range(1):
    print('Logistic Regression:',performance(lr,x_test,y_test))
    print('SVM:',performance(svm,x_test,y_test))
    print('Random Forest:',performance(rf,x_test,y_test))

TypeError: performance() missing 2 required positional arguments: 'y_train' and 'y_test'

In [178]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [179]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [180]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [181]:
folds

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [209]:
score_lr = []
score_svm = []
score_rf = []
for train_index, test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test = train_test_split(digits.data[train_index],digits.target[train_index])
    score_lr.append(performance(lr,x_train,x_test,y_train,y_test))
    score_svm.append(performance(svm,x_train,x_test,y_train,y_test))
    score_rf.append(performance(rf,x_train,x_test,y_train,y_test))

In [210]:
score_lr

[1.0, 1.0, 1.0]

In [211]:
score_svm

[0.9966666666666667, 1.0, 0.9933333333333333]

In [213]:
# Second method to check the best score by the model
from sklearn.model_selection import cross_val_score

In [214]:
cross_val_score(lr,digits.data,digits.target,cv=5)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [215]:
cross_val_score(svm,digits.data,digits.target,cv=5)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [216]:
cross_val_score(rf,digits.data,digits.target,cv=5)

array([0.93333333, 0.90277778, 0.96935933, 0.9637883 , 0.91643454])